# Generated by Django 4.0.5 on 2022-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_name', models.CharField(max_length=1000)),
                ('difficulty', models.CharField(max_length=10)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('totalsubmissions', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Problems',
            },
        ),
    ]
