# Generated by Django 4.0.5 on 2022-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='prob_name',
            field=models.CharField(max_length=100),
        ),
    ]
