# Generated by Django 4.0.5 on 2022-06-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_app', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='prob_app.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=40),
        ),
    ]
