# Generated by Django 4.0.5 on 2022-06-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prob_app', '0004_problem_tags_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='prob_app.tag'),
        ),
    ]
