# Generated by Django 4.0.5 on 2022-06-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prob_app', '0005_remove_problem_tags_problem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
    ]
