# Generated by Django 4.0.5 on 2022-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_app', '0006_remove_problem_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_statment', models.CharField(max_length=1000)),
                ('prob_solution', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.TextField(max_length=1000)),
                ('outputs', models.TextField(max_length=1000)),
            ],
        ),
    ]
