# Generated by Django 4.0.5 on 2022-06-30 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prob_app', '0007_problemdescription_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_desc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='prob_app.problemdescription'),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='prob_app.testcase'),
        ),
        migrations.AlterField(
            model_name='problemdescription',
            name='prob_solution',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='problemdescription',
            name='prob_statment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
