# Generated by Django 4.0.5 on 2022-07-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_app', '0008_problem_problem_desc_problem_test_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='prob_app.tag'),
        ),
        migrations.AlterField(
            model_name='problemdescription',
            name='prob_solution',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='problemdescription',
            name='prob_statment',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
