# Generated by Django 4.0.5 on 2022-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prob_app', '0009_problem_tags_alter_problemdescription_prob_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(default=800),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='prob_app.tag'),
        ),
    ]
