# Generated by Django 4.0.5 on 2022-07-07 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileFieldView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(default=800)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('totalsubmissions', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Problems',
            },
        ),
        migrations.CreateModel(
            name='ProblemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_statement', models.TextField(blank=True, max_length=1000)),
                ('prob_solution', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='default', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.TextField(max_length=1000)),
                ('outputs', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apis.problem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Apis.filefieldview')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('email', models.EmailField(default='email@email.com', max_length=50)),
                ('username', models.CharField(default='username', max_length=20)),
                ('picture', models.URLField(default='http://www.example.com', max_length=100)),
                ('submissions', models.ManyToManyField(to='Apis.usersubmission')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_desc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apis.problemdescription'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(default='default', related_name='tags', to='Apis.tag'),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apis.testcase'),
        ),
    ]
