# Generated by Django 4.0.5 on 2022-07-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_statment', models.TextField(blank=True, max_length=1000)),
                ('prob_solution', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='default', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.TextField(max_length=1000)),
                ('outputs', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob_name', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(default=800)),
                ('accepted_submissions', models.IntegerField(default=0)),
                ('totalsubmissions', models.IntegerField(default=0)),
                ('problem_desc', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apis.problemdescription')),
                ('tags', models.ManyToManyField(default='default', related_name='tags', to='Apis.tag')),
                ('test_cases', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Apis.testcase')),
            ],
            options={
                'verbose_name_plural': 'Problems',
            },
        ),
    ]
