# Generated by Django 4.0.5 on 2022-07-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='inputs',
            field=models.FileField(upload_to='problems/inputs'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='outputs',
            field=models.FileField(upload_to='problems/outputs'),
        ),
    ]
