# Generated by Django 4.0.5 on 2022-07-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0002_alter_testcase_inputs_alter_testcase_outputs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputFileFieldView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_outputs')),
            ],
        ),
        migrations.RenameModel(
            old_name='FileFieldView',
            new_name='CodeFileFieldView',
        ),
        migrations.AddField(
            model_name='user',
            name='op_submissions',
            field=models.ManyToManyField(to='Apis.outputfilefieldview'),
        ),
    ]
