# Generated by Django 4.0.5 on 2022-07-07 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0004_rename_codefilefieldview_codefile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
