# Generated by Django 4.0.5 on 2022-07-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0007_alter_usersubmission_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='Apis.codefile'),
        ),
    ]
