# Generated by Django 4.0.5 on 2022-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0010_alter_usersubmission_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
