# Generated by Django 4.0.5 on 2022-07-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apis', '0011_user_jwt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt',
        ),
    ]
